let movies = [
  {
    id: 1,
    title: 'Shutter Island',
    rating: 8.2,
    awards: true,
    length: 138,
    price: 80000000,
    genre: 'Suspenso',
  },
  {
    id: 2,
    title: 'The Revenant',
    rating: 8,
    awards: true,
    length: 156,
    price: 135000000,
    genre: 'Aventura',
  },
  {
    id: 3,
    title: 'The Dark Knight',
    rating: 9,
    awards: true,
    length: 152,
    price: 185000000,
    genre: 'Acción',
  },
  {
    id: 4,
    title: 'Spirited Away',
    rating: 8.6,
    awards: true,
    length: 125,
    price: 15000000,
    genre: 'Animación',
  },
  {
    id: 5,
    title: 'Blade Runner 2049',
    rating: 8,
    awards: true,
    length: 164,
    price: 150000000,
    genre: 'Ciencia ficción',
  },
  {
    id: 6,
    title: 'Rush Hour',
    rating: 7,
    awards: true,
    length: 98,
    price: 35000000,
    genre: 'Comedia',
  },
];

module.exports = movies;
